//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostSap_GR_TR
{
    using PostSap_GR_TR.Class;
    using PostSap_GR_TR.Models;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class BarcodeEntities : DbContext
    {
        public BarcodeEntities()
            : base("name=BarcodeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_sap_batch_gr> v_sap_batch_gr { get; set; }
        public virtual DbSet<T_LOG_GR_STOCK> T_LOG_GR_STOCK { get;  set; }
        public virtual DbSet<T_LOG_STOCK_ERROR> T_LOG_STOCK_ERROR { get; set; }
        public virtual DbSet<T_LOCATION_SAP> T_LOCATION_SAP { get; set; }
        public virtual DbSet<T_LOG_ADD_STOCK> T_LOG_ADD_STOCK { get; set; }
    }
}
